In [3]:
import pandas as pd

In [4]:
data = {
    "Moisture": [12.5, 15.0, 18.5, 13.0, 16.2],
    "Foreign_Matter": [1.2, 2.5, 3.0, 1.5, 2.0],
    "Damaged_Grains": [2.0, 3.5, 4.0, 2.5, 3.0]
}

df = pd.DataFrame(data)

df

   Moisture  Foreign_Matter  Damaged_Grains
0      12.5             1.2             2.0
1      15.0             2.5             3.5
2      18.5             3.0             4.0
3      13.0             1.5             2.5
4      16.2             2.0             3.0

In [5]:
def predict_grade(row):

    if row["Moisture"] < 14 and row["Foreign_Matter"] < 2 and row["Damaged_Grains"] < 3:
        return "A"

    elif row["Moisture"] <= 17:
        return "B"

    else:
        return "C"

In [6]:
df["Predicted_Grade"] = df.apply(predict_grade, axis=1)

df

   Moisture  Foreign_Matter  Damaged_Grains Predicted_Grade
0      12.5             1.2             2.0               A
1      15.0             2.5             3.5               B
2      18.5             3.0             4.0               C
3      13.0             1.5             2.5               A
4      16.2             2.0             3.0               B